# Generated by Django 5.0.14 on 2026-04-30 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_delegationmarketsegment_delegationmarketsnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("base_url", models.URLField(max_length=500)),
                (
                    "scraper_class",
                    models.CharField(
                        help_text="Registry key, e.g. TayaraScraper", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("max_listings", models.IntegerField(default=100)),
                (
                    "schedule_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Minimum hours between scrape runs for this source",
                    ),
                ),
                ("last_scraped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        default="system",
                        help_text="Who/what triggered this job: system, api, cron, manual",
                        max_length=100,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("urls_discovered", models.IntegerField(default=0)),
                ("records_scraped", models.IntegerField(default=0)),
                ("records_normalized", models.IntegerField(default=0)),
                ("records_imported", models.IntegerField(default=0)),
                ("records_duplicates", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("error_log", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="scraper.scrapesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapedListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="SHA-1 hash of source|url|title — deduplication key",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("source_url", models.URLField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("raw", "Raw"),
                            ("normalized", "Normalized"),
                            ("imported", "Imported"),
                            ("duplicate", "Duplicate"),
                            ("failed", "Failed"),
                        ],
                        default="raw",
                        max_length=20,
                    ),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("normalized_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("normalized_at", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duplicate_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="scraper.scrapedlisting",
                    ),
                ),
                (
                    "property",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraped_listing",
                        to="core.property",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraped_listings",
                        to="scraper.scrapejob",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_listings",
                        to="scraper.scrapesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="scraper_scr_status_2f26b0_idx"
                    ),
                    models.Index(
                        fields=["source", "status"],
                        name="scraper_scr_source__a179c8_idx",
                    ),
                    models.Index(
                        fields=["scraped_at"], name="scraper_scr_scraped_40c5ff_idx"
                    ),
                ],
            },
        ),
    ]
