# Generated by Django 4.2.10 on 2026-04-04 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=25,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Tunisian phone number.",
                                regex="^\\+?2?1?6?\\d{8}$",
                            )
                        ],
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("learner", "Learner"),
                            ("contributor", "Contributor"),
                            ("volunteer", "Research Volunteer"),
                            ("ambassador", "Community Ambassador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
