# Generated by Django 5.0.14 on 2026-04-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="participant",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Participants",
            },
        ),
    ]
