# Generated by Django 5.0.14 on 2026-05-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuationrequest",
            name="climate_adjusted_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuationrequest",
            name="climate_adjustment_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="valuationrequest",
            name="climate_label",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="valuationrequest",
            name="climate_risk_category",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
