# Generated by Django 4.2.10 on 2026-05-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delegation_price_benchmarks"),
        ("valuation", "0006_remove_forecast_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegationForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delegation_name", models.CharField(db_index=True, max_length=255)),
                (
                    "governorate",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("forecast_origin", models.DateField()),
                ("forecast_month", models.DateField()),
                ("horizon_idx", models.IntegerField()),
                ("predicted_price_per_m2", models.FloatField()),
                ("model_mape_pct", models.FloatField(default=2.92)),
                ("model_version", models.CharField(default="h12_v1", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delegation_fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forecasts",
                        to="core.delegation",
                    ),
                ),
            ],
            options={
                "ordering": ["delegation_name", "horizon_idx"],
                "indexes": [
                    models.Index(
                        fields=["delegation_name", "forecast_origin"],
                        name="valuation_d_delegat_2aee2f_idx",
                    ),
                    models.Index(
                        fields=["governorate", "horizon_idx"],
                        name="valuation_d_governo_09b533_idx",
                    ),
                    models.Index(
                        fields=["governorate", "forecast_origin"],
                        name="valuation_d_governo_e04d66_idx",
                    ),
                ],
                "unique_together": {
                    ("delegation_name", "forecast_origin", "horizon_idx")
                },
            },
        ),
    ]
