# Generated by Django 5.0.14 on 2026-04-24 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_useractivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=255)),
                ("purchase_price", models.FloatField()),
                ("current_value", models.FloatField()),
                ("monthly_rent", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_id", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("price", models.FloatField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserValuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("estimated_price", models.FloatField()),
                ("input_surface", models.FloatField(blank=True, null=True)),
                ("input_location", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="users_usera_user_id_421934_idx",
            old_name="users_userac_user_id_49d74d_idx",
        ),
        migrations.RenameIndex(
            model_name="useractivity",
            new_name="users_usera_created_828ca1_idx",
            old_name="users_userac_created_d8fb39_idx",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_assets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedproperty",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_properties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="uservaluation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_valuations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(
                fields=["user", "created_at"], name="users_portf_user_id_7925b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedproperty",
            index=models.Index(
                fields=["user", "created_at"], name="users_saved_user_id_f649c8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedproperty",
            constraint=models.UniqueConstraint(
                fields=("user", "property_id"), name="unique_saved_property_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="uservaluation",
            index=models.Index(
                fields=["user", "created_at"], name="users_userv_user_id_074305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uservaluation",
            index=models.Index(
                fields=["user", "input_location"], name="users_userv_user_id_9757ee_idx"
            ),
        ),
    ]
