# Generated by Django 5.0.14 on 2026-04-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_portfolio_savedproperty_uservaluation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("valuation", "Valuation"),
                    ("analysis", "Analysis"),
                    ("simulation", "Simulation"),
                    ("legal", "Legal Session"),
                    ("explore", "Explore"),
                    ("save_property", "Save Property"),
                    ("cta_click", "CTA Click"),
                ],
                max_length=30,
            ),
        ),
    ]
