# Generated by Django 5.2.13 on 2026-04-15 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["-updated_at"], "verbose_name_plural": "Properties"},
        ),
        migrations.AlterField(
            model_name="property",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.region",
            ),
        ),
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("population", models.IntegerField(default=0)),
                ("centroid_lat", models.FloatField(blank=True, null=True)),
                ("centroid_lon", models.FloatField(blank=True, null=True)),
                ("geojson_polygon", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations",
                        to="core.region",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("region", "name")},
            },
        ),
        migrations.AddField(
            model_name="property",
            name="delegation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.delegation",
            ),
        ),
    ]
