# Generated by Django 5.0.14 on 2026-04-30 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_property_options_alter_property_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelegationMarketSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_type", models.CharField(default="all", max_length=20)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("sale", "Sale"), ("rent", "Rent")], max_length=10
                    ),
                ),
                ("listing_count", models.IntegerField(default=0)),
                ("median_price", models.FloatField(blank=True, null=True)),
                ("avg_price", models.FloatField(blank=True, null=True)),
                ("median_price_per_sqm", models.FloatField(blank=True, null=True)),
                ("avg_price_per_sqm", models.FloatField(blank=True, null=True)),
                ("min_price", models.FloatField(blank=True, null=True)),
                ("max_price", models.FloatField(blank=True, null=True)),
                ("avg_surface_sqm", models.FloatField(blank=True, null=True)),
                ("median_surface_sqm", models.FloatField(blank=True, null=True)),
                ("median_days_on_market", models.FloatField(blank=True, null=True)),
                (
                    "trend_direction",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("forecast_3m", models.FloatField(blank=True, null=True)),
                ("forecast_6m", models.FloatField(blank=True, null=True)),
                ("forecast_12m", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": [
                    "snapshot__delegation__name",
                    "property_type",
                    "transaction_type",
                ],
            },
        ),
        migrations.CreateModel(
            name="DelegationMarketSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("as_of_date", models.DateField()),
                ("listing_count", models.IntegerField(default=0)),
                ("sale_listing_count", models.IntegerField(default=0)),
                ("rent_listing_count", models.IntegerField(default=0)),
                ("median_sale_price", models.FloatField(blank=True, null=True)),
                ("median_rent_price", models.FloatField(blank=True, null=True)),
                ("avg_sale_price", models.FloatField(blank=True, null=True)),
                ("avg_rent_price", models.FloatField(blank=True, null=True)),
                ("median_price_per_sqm", models.FloatField(blank=True, null=True)),
                (
                    "price_per_sqm_distribution",
                    models.JSONField(blank=True, default=dict),
                ),
                ("supply_pressure", models.FloatField(default=0)),
                ("median_days_on_market", models.FloatField(blank=True, null=True)),
                (
                    "climate_risk_level",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "heat_risk_level",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("sustainability_score", models.FloatField(blank=True, null=True)),
                (
                    "trend_direction",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("forecast_3m", models.FloatField(blank=True, null=True)),
                ("forecast_6m", models.FloatField(blank=True, null=True)),
                ("forecast_12m", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "delegation__region__governorate",
                    "delegation__name",
                    "-as_of_date",
                ],
            },
        ),
        migrations.AddField(
            model_name="property",
            name="currency",
            field=models.CharField(default="TND", max_length=10),
        ),
        migrations.AddField(
            model_name="property",
            name="location_raw",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="property",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="price_per_sqm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="rooms",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="scraped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="transaction_type",
            field=models.CharField(
                choices=[("sale", "Sale"), ("rent", "Rent")],
                default="sale",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("villa", "Villa"),
                    ("land", "Land"),
                    ("commercial", "Commercial"),
                    ("office", "Office"),
                    ("farm", "Farm"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["delegation", "transaction_type"],
                name="core_proper_delegat_172e20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["posted_at"], name="core_proper_posted__a1ffe5_idx"
            ),
        ),
        migrations.AddField(
            model_name="delegationmarketsnapshot",
            name="delegation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_snapshots",
                to="core.delegation",
            ),
        ),
        migrations.AddField(
            model_name="delegationmarketsegment",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segments",
                to="core.delegationmarketsnapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="delegationmarketsnapshot",
            constraint=models.UniqueConstraint(
                fields=("delegation", "as_of_date"),
                name="unique_snapshot_per_delegation_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="delegationmarketsegment",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "property_type", "transaction_type"),
                name="unique_market_segment_per_snapshot",
            ),
        ),
    ]
