# Generated by Django 5.0.14 on 2026-05-01 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delegationmarketsegment_delegationmarketsnapshot_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="climaterisk",
            options={
                "verbose_name": "Climate Risk Assessment",
                "verbose_name_plural": "Climate Risk Assessments",
            },
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="avg_rainfall_mm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="avg_temp_c",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="climate_region",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="combined_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="days_above_35c",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="drought_risk",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very_high", "Very High"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="drought_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="earthquake_risk",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very_high", "Very High"),
                ],
                default="low",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="earthquake_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="flood_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="heat_risk_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="infrastructure_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="is_coastal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="livability_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="max_summer_temp_c",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="price_adjustment_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="risk_category",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Moderate", "Moderate"),
                    ("High", "High"),
                    ("Very High", "Very High"),
                ],
                default="Moderate",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="scenario_2c",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="scenario_4c",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="scenario_baseline",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="sea_level_exposure",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="climaterisk",
            name="sustainability_grade",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D"), ("F", "F")],
                default="C",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="climaterisk",
            name="flood_risk",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very_high", "Very High"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="climaterisk",
            name="heat_stress_risk",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("very_high", "Very High"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="climaterisk",
            name="sustainability_score",
            field=models.FloatField(
                default=50,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
