# Generated by Django 5.0.14 on 2026-05-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_climaterisk_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "Apartment"),
                    ("house", "House"),
                    ("commercial", "Commercial"),
                    ("land", "Land"),
                ],
                max_length=20,
            ),
        ),
    ]
