# Generated by Django 4.2.10 on 2026-05-06 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scenario_name", models.CharField(db_index=True, max_length=64)),
                ("agent_scale", models.CharField(default="tiny", max_length=16)),
                ("num_months", models.PositiveSmallIntegerField(default=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("current_month", models.PositiveSmallIntegerField(default=0)),
                ("total_transactions", models.PositiveIntegerField(default=0)),
                (
                    "avg_transaction_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("monthly_states", models.JSONField(default=list)),
                ("agent_outcomes", models.JSONField(default=list)),
                ("final_metrics", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="simulation__status_14430d_idx",
                    ),
                    models.Index(
                        fields=["scenario_name", "created_at"],
                        name="simulation__scenari_057900_idx",
                    ),
                ],
            },
        ),
    ]
